[package]
name = "clashtui"
version = "0.1.0"
edition = "2021"

authors = ["Johan Chane <johanchanex@gmail.com>"]
description = "Mihomo TUI Client"
license = "MIT"
repository = "https://github.com/JohanChane/clashtui"
homepage = "https://github.com/JohanChane/clashtui"
documentation = "https://github.com/JohanChane/clashtui"
readme = "README.md"

exclude = [
  "PKGBUILD",
  "Scoop/*",
  "App/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = { version = "0.25.0", features = ["all-widgets", "serde"] }
crossterm = { version = "0.27" }
serde = { version = "1.0", features = ["derive"] }
argh = { version = "0.1.0" }
reqwest = { version = "0.11.22", features = ["blocking"] } #"socks"
serde_derive = "1.0"
serde_yaml = "0.9"
serde_json = "1.0"
#toml = "0.8.8"
anyhow = "1.0"
#once_cell = "1.14.0"
log = "0.4"
#env_logger = "0.10"
log4rs = "1.2"
#[cfg(target_os = "windows")]
encoding = "0.2.33"
