name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Mihomo
      run: |
        wget --output-document mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-linux-amd64-v1.18.0.gz
        gunzip mihomo.gz
        chmod +x mihomo
        nohup ./mihomo -d Example -f Example/basic_clash_config.yaml &
      
    - name: Cache Crates
      uses: actions/cache@v4
      with:
        path: |
          ./target
          ~/.cargo            
        key: debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
          debug-${{ runner.os }}-  

    - name: Download Dependencies
      run: cd clashtui && cargo fetch
    - name: Run tests
      run: cd clashtui && cargo test --verbose
    - name: Build
      run: cd clashtui && cargo build --verbose && cargo build --release

    - name: Build Release
      run: |
        mkdir artifacts_linux
        mv ./clashtui/target/release/clashtui ./artifacts_linux/clashtui_r
        mv ./clashtui/target/debug/clashtui ./artifacts_linux/clashtui_d

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: artifacts_linux

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache Crates
      uses: actions/cache@v4
      with:
        path: |
          ./clashtui/target
          ~/.cargo            
        key: debug-${{ runner.os }}-${{ hashFiles('./clashtui/rust-toolchain.toml') }}-${{ hashFiles('./clashtui/Cargo.lock') }}
        restore-keys: |
          debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
          debug-${{ runner.os }}-   

    - name: Download Dependencies
      run: cd clashtui && cargo fetch
    # - name: Run tests
    #   run: cd clashtui && cargo test --verbose
    - name: Build
      run: cd clashtui && cargo build --verbose && cargo build --release

    - name: Build Release
      run: |
        tree
      # mkdir artifacts_windows
      # mv ./target/release/clashtui ./artifacts_windows/clashtui_r
      # mv ./target/debug/clashtui ./artifacts_windows/clashtui_d

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: artifacts_windows

  release:
    runs-on: ubuntu-latest

    needs: [build-linux, build-windows]

    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifact/*
